In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import f1_score, accuracy_score, recall_score, precision_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
data_a = pd.read_csv('./1/protocol_a.csv')
data_b = pd.read_csv('./1/protocol_b.csv')
data_c = pd.read_csv('./1/protocol_c.csv')

In [3]:
data_a.head()

Unnamed: 0           src_ip  sport          dst_ip  dport  proto  \
0           0     136.197.19.4  51287   170.14.68.136    443      6   
1           1  220.108.181.128  50844    18.239.73.44    443      6   
2           2     67.1.238.148  59058  132.30.134.212    443      6   
3           3    240.85.18.147  47326  207.211.80.120    443      6   
4           4  161.245.219.215  58184   49.120.135.43    443      6   

   payload_bytes_0  payload_bytes_1  payload_bytes_2  \
0              NaN              NaN              NaN   
1              NaN              NaN              NaN   
2              NaN              NaN              NaN   
3              NaN              NaN              NaN   
4              NaN              NaN              NaN   

                                     payload_bytes_3  ... pkt_len_3 pkt_len_4  \
0  1603010200010001fc03030f02fc6e9aa20d56bdc474ff...  ...       537        20   
1  1603010200010001fc0303eb7d7e5e38e3aa32ec95fb75...  ...       549        32   
2  1603010288010002840303e82a92a45517967db5e4baa3...  ...       685        32   
3  1603010200010001fc0303da68769d6531585531e14d98...  ...       549        32   
4  160301022f0100022b0303b2e772abd3c0a772b5df08d2...  ...       596        32   

  pkt_len_5 pkt_len_6 pkt_len_7 pkt_len_8 pkt_len_9 pkt_len_10 pkt_len_11  \
0      1240      1240      1240       848        20         20        113   
1      1240      1240        32        32        32         32        112   
2       296        32       112       130       961        335         93   
3       504      1240       189        44        32         32         32   
4      1430      1430      1430        66        32         32         32   

   pkt_len_12  
0          20  
1         542  
2          63  
3          32  
4          32  

[5 rows x 45 columns]

In [4]:
data_a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 45 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        2000 non-null   int64  
 1   src_ip            2000 non-null   object 
 2   sport             2000 non-null   int64  
 3   dst_ip            2000 non-null   object 
 4   dport             2000 non-null   int64  
 5   proto             2000 non-null   int64  
 6   payload_bytes_0   0 non-null      float64
 7   payload_bytes_1   0 non-null      float64
 8   payload_bytes_2   0 non-null      float64
 9   payload_bytes_3   1984 non-null   object 
 10  payload_bytes_4   233 non-null    object 
 11  payload_bytes_5   1878 non-null   object 
 12  payload_bytes_6   1593 non-null   object 
 13  payload_bytes_7   1689 non-null   object 
 14  payload_bytes_8   1169 non-null   object 
 15  payload_bytes_9   890 non-null    object 
 16  payload_bytes_10  797 non-null    object 


In [5]:
data_b.head()

Unnamed: 0           src_ip  sport        dst_ip  dport  proto  \
0           0   94.135.187.230  64022  10.5.192.100    443      6   
1           1   94.135.187.230  57478  10.54.63.151    443      6   
2           2   94.135.187.230  57643   10.54.63.41    443      6   
3           3  184.164.110.238  39970  10.5.192.100    443      6   
4           4  172.240.139.106  45956   10.54.63.50    443      6   

   payload_bytes_0  payload_bytes_1  payload_bytes_2  \
0              NaN              NaN              NaN   
1              NaN              NaN              NaN   
2              NaN              NaN              NaN   
3              NaN              NaN              NaN   
4              NaN              NaN              NaN   

                                     payload_bytes_3  ... pkt_len_3 pkt_len_4  \
0  a0adf946c8228d95ca60f19d2d93fe850c59ec2137d73e...  ...       313       161   
1  e307366f0f76a6a62dd35b38b5e2d33a37dc2ba9a935ca...  ...       321       213   
2  521e2e373718aeb04b6a959a64cdba1bd2ab08ac6982ab...  ...       361       269   
3  edc3c16e73d4d231c968bb11c12fdddc69420570c61d7c...  ...      1109      1260   
4  d322033447d211a854321f1565eb3b7b33a7de928437a9...  ...       377      1260   

  pkt_len_5 pkt_len_6 pkt_len_7 pkt_len_8 pkt_len_9 pkt_len_10 pkt_len_11  \
0       141       189        20       672      1260       1260       1260   
1       269       125       189       189       493         20        301   
2       221        20      1260      1064        20        253         20   
3      1260      1260       492      1260        32         32         32   
4      1260      1260      1156        32       297         32         32   

   pkt_len_12  
0        1260  
1          20  
2         189  
3          32  
4          32  

[5 rows x 45 columns]

In [6]:
data_b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 45 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        161 non-null    int64  
 1   src_ip            161 non-null    object 
 2   sport             161 non-null    int64  
 3   dst_ip            161 non-null    object 
 4   dport             161 non-null    int64  
 5   proto             161 non-null    int64  
 6   payload_bytes_0   0 non-null      float64
 7   payload_bytes_1   0 non-null      float64
 8   payload_bytes_2   0 non-null      float64
 9   payload_bytes_3   132 non-null    object 
 10  payload_bytes_4   148 non-null    object 
 11  payload_bytes_5   90 non-null     object 
 12  payload_bytes_6   126 non-null    object 
 13  payload_bytes_7   119 non-null    object 
 14  payload_bytes_8   121 non-null    object 
 15  payload_bytes_9   120 non-null    object 
 16  payload_bytes_10  121 non-null    object 
 1

In [7]:
data_c.head()

Unnamed: 0          src_ip  sport          dst_ip  dport  proto  \
0           0  172.17.240.131  46500  130.87.143.208    443      6   
1           1  172.17.240.131  60650  130.87.143.208    443      6   
2           2  172.17.240.131  60640  130.87.143.208    443      6   
3           3  172.17.240.131  60630  130.87.143.208    443      6   
4           4  172.17.240.131  60616  130.87.143.208    443      6   

   payload_bytes_0  payload_bytes_1  payload_bytes_2  \
0              NaN              NaN              NaN   
1              NaN              NaN              NaN   
2              NaN              NaN              NaN   
3              NaN              NaN              NaN   
4              NaN              NaN              NaN   

                                     payload_bytes_3  ... pkt_len_3 pkt_len_4  \
0  84379e4c6b950de7d01dcf1c80b377531b6165f416fdf5...  ...       149        32   
1  2915f2be64819714cd2ac4cee79ac715738a4b14b2e227...  ...       105        32   
2  d9194a87f3cdbed32688d53e7e6c23c53889cea1ceea1a...  ...       105       583   
3  844b33de5b077083bac4438df540d746bdd01e7fd96ac5...  ...       105        32   
4  784f5bbc9ac58a7d40ca18c43487cec711a3ddb73c3273...  ...       105       583   

  pkt_len_5 pkt_len_6 pkt_len_7 pkt_len_8 pkt_len_9 pkt_len_10 pkt_len_11  \
0       253        32        32        40        40         32        622   
1       583        32      1380      1380        32         32       1016   
2        32        32      1380      1380        32         32       1380   
3       583        32      1380      1380        32       1380       1380   
4        32        32      1380      1380      1380         32         32   

   pkt_len_12  
0          32  
1          32  
2        1380  
3          32  
4          32  

[5 rows x 45 columns]

In [8]:
data_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 45 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        1000 non-null   int64  
 1   src_ip            1000 non-null   object 
 2   sport             1000 non-null   int64  
 3   dst_ip            1000 non-null   object 
 4   dport             1000 non-null   int64  
 5   proto             1000 non-null   int64  
 6   payload_bytes_0   0 non-null      float64
 7   payload_bytes_1   0 non-null      float64
 8   payload_bytes_2   0 non-null      float64
 9   payload_bytes_3   1000 non-null   object 
 10  payload_bytes_4   107 non-null    object 
 11  payload_bytes_5   893 non-null    object 
 12  payload_bytes_6   280 non-null    object 
 13  payload_bytes_7   905 non-null    object 
 14  payload_bytes_8   716 non-null    object 
 15  payload_bytes_9   550 non-null    object 
 16  payload_bytes_10  462 non-null    object 
 

In [9]:
readme = pd.read_csv('./1/read_me.csv')
readme = readme[['Признак', 'Описание']]

In [10]:
readme

Признак                                           Описание
0                src_ip                                 IP-адрес источника
1                 sport                                     Порт источника
2                dst_ip                                IP-адрес получателя
3                 dport                                    Порт получателя
4                 proto                              Транспортный протокол
5  payload_bytes_0...12  Последовательности байт информационных частей ...
6      direction_0...12                Направления передачи пакетов 0...12
7        pkt_len_0...12                               Длины пакетов 0...12

In [11]:
#Deletion
# data_a = data_a.drop(columns=['payload_bytes_0', 'payload_bytes_1', 'payload_bytes_2', 'proto'])
# data_b = data_b.drop(columns=['payload_bytes_0', 'payload_bytes_1', 'payload_bytes_2', 'proto'])
# data_c = data_c.drop(columns=['payload_bytes_0', 'payload_bytes_1', 'payload_bytes_2', 'proto'])

In [12]:
len(data_c['payload_bytes_12'].unique())

327

In [13]:
len(data_c['pkt_len_0'].unique())

1

In [14]:
data_a['pkt_len_3'].unique()

array([ 537,  549,  685,  596,  286,  225,  577,  844,  634,  822,  617,
        655,  632,  216,  605,  630,  615,  570,  778,  586,  679,  564,
        681,  684,  255,  599,  562,  603,  775,  740,  680,  207,  567,
        215,  239,  633,  666,  635,  649,  308,  601,  611,  553,  574,
        619,  616,  583,  204,  168,  582,  368,  336,  554,  763,  606,
        618,  613,  338,   36, 1171,  687,  810,  264, 1177,  552, 1432,
        622,  764,  937,  933,  563,  767,  645,  598,  836,  837,  690,
        637,  212,  607,  711,  589,  863,  692,  704,  727,  597,  631,
        319,  703,  901,  232,  344,  600,  668,  555,  249,  595,  219,
        172,  714,  234,  221,  439,  403,   40,  638,  738,  852,  200,
         32,  612,  594,  674,  741,  217,  551,  742,  825,  236,  838,
        777,  761,  793,  628,  561,  148,  559,  581,  291,  841,  557,
        370,  745,  602,  629,  827,  560,  820,  839,  580,  945,  788,
        199,  187,  731,  868,  525,  186,  801,  2

In [15]:
data_b['pkt_len_3'].unique()

array([ 313,  321,  361, 1109,  377,  425,  345, 1260,  217,  201,  473,
        722,  393, 1056,  185, 1028, 1220,  233,  178,  537, 1253,  489,
        281,  265, 1156, 1045,  770,  457, 1092, 1204,  914,   44,  237,
        409,  610,  898, 1060,  530,  834, 1042,  137,  738,   60,  329,
        498,  249,  754,  562, 1074,  297,  441, 1176, 1320,  301, 1106,
       1140,  674, 1093], dtype=int64)

In [16]:
data_c['pkt_len_3'].unique()

array([149, 105, 761, 622, 717, 519, 733, 526, 743, 748, 673, 722, 765,
       518, 528, 533, 510, 707, 710, 703, 702, 546, 555, 549, 543, 716,
       547, 711, 712, 715, 522, 713, 692], dtype=int64)

In [17]:
data_a['payload_bytes_3'].head()

0    1603010200010001fc03030f02fc6e9aa20d56bdc474ff...
1    1603010200010001fc0303eb7d7e5e38e3aa32ec95fb75...
2    1603010288010002840303e82a92a45517967db5e4baa3...
3    1603010200010001fc0303da68769d6531585531e14d98...
4    160301022f0100022b0303b2e772abd3c0a772b5df08d2...
Name: payload_bytes_3, dtype: object

In [18]:
data_a['payload_bytes_3'].str.slice(0,4).unique()

array(['1603', '4544', nan, '1403', 'd500'], dtype=object)

In [19]:
#data_b['payload_bytes_3'].str.slice(0,3).unique()

In [20]:
#data_c['payload_bytes_3'].str.slice(0,3).unique()

In [21]:
# data_a['payload_bytes_3'].apply(lambda x: print(x[0:4]))

In [22]:
# for i in range(len(data_a['payload_bytes_3'])):
#     val = data_a['payload_bytes_3'][i][1]
#     pb3_a.append(val)

In [23]:
# data_a['payload_bytes_3'].apply(lambda x: pb3_a.append(x[0:4]))

In [24]:
np.sort(data_a['pkt_len_0'].unique())

array([24, 32, 36, 40, 44], dtype=int64)

In [25]:
np.sort(data_b['pkt_len_0'].unique())

array([32, 40, 44], dtype=int64)

In [26]:
np.sort(data_c['pkt_len_0'].unique())

array([40], dtype=int64)

Bad: 2, 4, 6, 7, 8, 9, 12
Good: 
?: 3, 5, 10, 11, 

In [27]:
matches = []

In [28]:
for i in (data_a['pkt_len_3'].unique()):
    for j in (data_b['pkt_len_3'].unique()):
        for k in (data_c['pkt_len_3'].unique()):
            if i == j:
                matches.append('{}, 1 and 2'.format(i))
            elif i == k:
                matches.append('{}, 1 and 3'.format(i))
            elif j == k:
                matches.append('{}, 2 and 3'.format(j))

In [29]:
matches = pd.Series(matches).drop_duplicates()

In [30]:
matches

0        722, 2 and 3
1        537, 1 and 2
34       549, 1 and 3
118      562, 1 and 2
190      622, 1 and 3
262      711, 1 and 3
323      692, 1 and 3
387      703, 1 and 3
451      555, 1 and 3
511      249, 1 and 2
555      738, 1 and 2
594      674, 1 and 2
628      217, 1 and 2
668      761, 1 and 3
765      526, 1 and 3
829      237, 1 and 2
863      673, 1 and 3
963     1320, 1 and 2
1008      44, 1 and 2
dtype: object

In [31]:
data_b['dst_ip'].unique()

array(['10.5.192.100', '10.54.63.151', '10.54.63.41', '10.54.63.50',
       '10.54.63.51'], dtype=object)

In [32]:
data_c['dst_ip'].unique()

array(['130.87.143.208'], dtype=object)

In [33]:
#direction_3, 5, 6, 8, 9, 10, 11, 12

In [34]:
data_a['direction_12'].unique()

array([-1,  1], dtype=int64)

In [35]:
data_b['direction_12'].unique()

array([-1,  1], dtype=int64)

In [36]:
data_c['direction_12'].unique()

array([-1,  1], dtype=int64)

In [37]:
data_a['protocol'] = '0'
data_b['protocol'] = '1'
data_c['protocol'] = '2'

In [38]:
data = pd.concat([data_a, data_b, data_c])

In [39]:
data.head()

Unnamed: 0           src_ip  sport          dst_ip  dport  proto  \
0           0     136.197.19.4  51287   170.14.68.136    443      6   
1           1  220.108.181.128  50844    18.239.73.44    443      6   
2           2     67.1.238.148  59058  132.30.134.212    443      6   
3           3    240.85.18.147  47326  207.211.80.120    443      6   
4           4  161.245.219.215  58184   49.120.135.43    443      6   

   payload_bytes_0  payload_bytes_1  payload_bytes_2  \
0              NaN              NaN              NaN   
1              NaN              NaN              NaN   
2              NaN              NaN              NaN   
3              NaN              NaN              NaN   
4              NaN              NaN              NaN   

                                     payload_bytes_3  ... pkt_len_4 pkt_len_5  \
0  1603010200010001fc03030f02fc6e9aa20d56bdc474ff...  ...        20      1240   
1  1603010200010001fc0303eb7d7e5e38e3aa32ec95fb75...  ...        32      1240   
2  1603010288010002840303e82a92a45517967db5e4baa3...  ...        32       296   
3  1603010200010001fc0303da68769d6531585531e14d98...  ...        32       504   
4  160301022f0100022b0303b2e772abd3c0a772b5df08d2...  ...        32      1430   

  pkt_len_6 pkt_len_7 pkt_len_8 pkt_len_9 pkt_len_10 pkt_len_11 pkt_len_12  \
0      1240      1240       848        20         20        113         20   
1      1240        32        32        32         32        112        542   
2        32       112       130       961        335         93         63   
3      1240       189        44        32         32         32         32   
4      1430      1430        66        32         32         32         32   

   protocol  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 46 columns]

In [40]:
data = data.drop(columns=[
    'payload_bytes_0', 
    'payload_bytes_1', 
    'payload_bytes_2', 
    'proto', 
    'Unnamed: 0', 
    'sport', 
    'dport', 
    'payload_bytes_4', 
    'payload_bytes_5', 
    'payload_bytes_6', 
    'payload_bytes_7', 
    'payload_bytes_8', 
    'payload_bytes_9', 
    'payload_bytes_10', 
    'payload_bytes_11', 
    'payload_bytes_12',
    'pkt_len_1',
    'pkt_len_2',
    'pkt_len_3',
    'pkt_len_4',
    'pkt_len_5',
    'pkt_len_6',
    'pkt_len_7',
    'pkt_len_8',
    'pkt_len_9',
    'pkt_len_10',
    'pkt_len_11',
    'pkt_len_12',
    'direction_0',
    'direction_1',
    'direction_2',
    'direction_4',
    'direction_7',
    'src_ip'
            ]
        )

In [41]:
data.reset_index(inplace=True, drop=True)
data

dst_ip                                    payload_bytes_3  \
0      170.14.68.136  1603010200010001fc03030f02fc6e9aa20d56bdc474ff...   
1       18.239.73.44  1603010200010001fc0303eb7d7e5e38e3aa32ec95fb75...   
2     132.30.134.212  1603010288010002840303e82a92a45517967db5e4baa3...   
3     207.211.80.120  1603010200010001fc0303da68769d6531585531e14d98...   
4      49.120.135.43  160301022f0100022b0303b2e772abd3c0a772b5df08d2...   
...              ...                                                ...   
3156  130.87.143.208  c5d22d815e125f38a7d21ba66c2693b7364b3dbc45918c...   
3157  130.87.143.208  9b3772c717b01007588073e1995aed9385180d898d2901...   
3158  130.87.143.208  bdf42bfa039e3f0ae477b8f40a8ad6f86d43d2b9eba9f9...   
3159  130.87.143.208  67169d3eda13a19c6248b0ef7f06824e0cd5bbca36565f...   
3160  130.87.143.208  d5272a28430835a39f15907ab81913129a4642559c93c8...   

      direction_3  direction_5  direction_6  direction_8  direction_9  \
0               1           -1           -1           -1            1   
1               1           -1           -1            1            1   
2               1           -1            1            1            1   
3               1           -1           -1            1            1   
4               1           -1           -1           -1            1   
...           ...          ...          ...          ...          ...   
3156            1           -1            1            1           -1   
3157            1           -1            1            1           -1   
3158            1           -1            1            1           -1   
3159            1           -1            1            1           -1   
3160            1           -1           -1            1           -1   

      direction_10  direction_11  direction_12  pkt_len_0 protocol  
0                1             1            -1         32        0  
1                1             1            -1         40        0  
2               -1            -1            -1         40        0  
3                1             1             1         40        0  
4                1             1             1         40        0  
...            ...           ...           ...        ...      ...  
3156            -1            -1             1         40        2  
3157            -1            -1             1         40        2  
3158            -1            -1             1         40        2  
3159            -1            -1            -1         40        2  
3160             1             1             1         40        2  

[3161 rows x 12 columns]

In [42]:
data = data.dropna()

In [43]:
data['payload_bytes_3'] = data['payload_bytes_3'].str.slice(0, 4)

C:\Users\emil_\AppData\Local\Temp\ipykernel_13996\317141445.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['payload_bytes_3'] = data['payload_bytes_3'].str.slice(0, 4)


In [44]:
data['payload_bytes_3'] = data['payload_bytes_3'].map(lambda x: 1 if x in ['1603', '4544', '1403', 'd500'] else 0)

C:\Users\emil_\AppData\Local\Temp\ipykernel_13996\1017386393.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['payload_bytes_3'] = data['payload_bytes_3'].map(lambda x: 1 if x in ['1603', '4544', '1403', 'd500'] else 0)


In [45]:
data['dst_ip'] = data['dst_ip'].map(lambda x: 1 if x == '130.87.143.208' else 0)

C:\Users\emil_\AppData\Local\Temp\ipykernel_13996\1176911959.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['dst_ip'] = data['dst_ip'].map(lambda x: 1 if x == '130.87.143.208' else 0)


In [46]:
data

dst_ip  payload_bytes_3  direction_3  direction_5  direction_6  \
0          0                1            1           -1           -1   
1          0                1            1           -1           -1   
2          0                1            1           -1            1   
3          0                1            1           -1           -1   
4          0                1            1           -1           -1   
...      ...              ...          ...          ...          ...   
3156       1                0            1           -1            1   
3157       1                0            1           -1            1   
3158       1                0            1           -1            1   
3159       1                0            1           -1            1   
3160       1                0            1           -1           -1   

      direction_8  direction_9  direction_10  direction_11  direction_12  \
0              -1            1             1             1            -1   
1               1            1             1             1            -1   
2               1            1            -1            -1            -1   
3               1            1             1             1             1   
4              -1            1             1             1             1   
...           ...          ...           ...           ...           ...   
3156            1           -1            -1            -1             1   
3157            1           -1            -1            -1             1   
3158            1           -1            -1            -1             1   
3159            1           -1            -1            -1            -1   
3160            1           -1             1             1             1   

      pkt_len_0 protocol  
0            32        0  
1            40        0  
2            40        0  
3            40        0  
4            40        0  
...         ...      ...  
3156         40        2  
3157         40        2  
3158         40        2  
3159         40        2  
3160         40        2  

[3116 rows x 12 columns]

In [47]:
X = data.drop(columns=['protocol'])
y = data['protocol']

In [48]:
y = y.astype(int)

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [50]:
models = [
    DecisionTreeClassifier(),
    GradientBoostingClassifier(), 
    RandomForestClassifier(),
    XGBClassifier(),
    CatBoostClassifier()
]

In [51]:
def make_prediction(m, X_train, y_train, X_test, y_test):
    model = m
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(
        'Accuracy:{:.2f} Precision:{:.2f} Recall:{:.2f} F1:{:.2f} '.format(
            accuracy_score(y_test, y_pred),
            precision_score(y_test, y_pred, average='micro'),
            recall_score(y_test, y_pred, average='micro'),
            f1_score(y_test, y_pred, average='micro'),
        )
    )

In [52]:
for i in models:
    print(i)
    make_prediction(
        m=i,
        X_train=X_train,
        y_train=y_train,
        X_test=X_test,
        y_test=y_test,
    )

DecisionTreeClassifier()
Accuracy:1.00 Precision:1.00 Recall:1.00 F1:1.00 
GradientBoostingClassifier()
Accuracy:1.00 Precision:1.00 Recall:1.00 F1:1.00 
RandomForestClassifier()
Accuracy:1.00 Precision:1.00 Recall:1.00 F1:1.00 
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)
Accuracy:1.00

174:	learn: 0.0007405	total: 590ms	remaining: 2.78s
175:	learn: 0.0007361	total: 593ms	remaining: 2.77s
176:	learn: 0.0007316	total: 595ms	remaining: 2.77s
177:	learn: 0.0007242	total: 598ms	remaining: 2.76s
178:	learn: 0.0007169	total: 601ms	remaining: 2.75s
179:	learn: 0.0007097	total: 603ms	remaining: 2.75s
180:	learn: 0.0007057	total: 606ms	remaining: 2.74s
181:	learn: 0.0006988	total: 609ms	remaining: 2.74s
182:	learn: 0.0006948	total: 612ms	remaining: 2.73s
183:	learn: 0.0006909	total: 615ms	remaining: 2.73s
184:	learn: 0.0006870	total: 618ms	remaining: 2.72s
185:	learn: 0.0006805	total: 621ms	remaining: 2.71s
186:	learn: 0.0006740	total: 623ms	remaining: 2.71s
187:	learn: 0.0006703	total: 626ms	remaining: 2.7s
188:	learn: 0.0006667	total: 629ms	remaining: 2.7s
189:	learn: 0.0006605	total: 632ms	remaining: 2.69s
190:	learn: 0.0006545	total: 634ms	remaining: 2.69s
191:	learn: 0.0006510	total: 637ms	remaining: 2.68s
192:	learn: 0.0006451	total: 640ms	remaining: 2.67s
193:	learn: 0.

392:	learn: 0.0002494	total: 1.18s	remaining: 1.82s
393:	learn: 0.0002486	total: 1.18s	remaining: 1.82s
394:	learn: 0.0002478	total: 1.19s	remaining: 1.82s
395:	learn: 0.0002470	total: 1.19s	remaining: 1.81s
396:	learn: 0.0002462	total: 1.19s	remaining: 1.81s
397:	learn: 0.0002454	total: 1.19s	remaining: 1.81s
398:	learn: 0.0002446	total: 1.2s	remaining: 1.8s
399:	learn: 0.0002438	total: 1.2s	remaining: 1.8s
400:	learn: 0.0002430	total: 1.2s	remaining: 1.8s
401:	learn: 0.0002423	total: 1.21s	remaining: 1.79s
402:	learn: 0.0002415	total: 1.21s	remaining: 1.79s
403:	learn: 0.0002407	total: 1.21s	remaining: 1.79s
404:	learn: 0.0002400	total: 1.21s	remaining: 1.78s
405:	learn: 0.0002392	total: 1.22s	remaining: 1.78s
406:	learn: 0.0002388	total: 1.22s	remaining: 1.78s
407:	learn: 0.0002383	total: 1.22s	remaining: 1.77s
408:	learn: 0.0002376	total: 1.22s	remaining: 1.77s
409:	learn: 0.0002368	total: 1.23s	remaining: 1.76s
410:	learn: 0.0002361	total: 1.23s	remaining: 1.76s
411:	learn: 0.0002

612:	learn: 0.0001495	total: 1.77s	remaining: 1.11s
613:	learn: 0.0001492	total: 1.77s	remaining: 1.11s
614:	learn: 0.0001491	total: 1.77s	remaining: 1.11s
615:	learn: 0.0001488	total: 1.77s	remaining: 1.11s
616:	learn: 0.0001485	total: 1.78s	remaining: 1.1s
617:	learn: 0.0001482	total: 1.78s	remaining: 1.1s
618:	learn: 0.0001479	total: 1.78s	remaining: 1.1s
619:	learn: 0.0001477	total: 1.79s	remaining: 1.09s
620:	learn: 0.0001475	total: 1.79s	remaining: 1.09s
621:	learn: 0.0001472	total: 1.79s	remaining: 1.09s
622:	learn: 0.0001469	total: 1.79s	remaining: 1.09s
623:	learn: 0.0001466	total: 1.8s	remaining: 1.08s
624:	learn: 0.0001463	total: 1.8s	remaining: 1.08s
625:	learn: 0.0001461	total: 1.8s	remaining: 1.08s
626:	learn: 0.0001458	total: 1.81s	remaining: 1.07s
627:	learn: 0.0001455	total: 1.81s	remaining: 1.07s
628:	learn: 0.0001452	total: 1.81s	remaining: 1.07s
629:	learn: 0.0001450	total: 1.81s	remaining: 1.06s
630:	learn: 0.0001447	total: 1.82s	remaining: 1.06s
631:	learn: 0.0001

837:	learn: 0.0001064	total: 2.37s	remaining: 459ms
838:	learn: 0.0001063	total: 2.37s	remaining: 456ms
839:	learn: 0.0001061	total: 2.38s	remaining: 453ms
840:	learn: 0.0001060	total: 2.38s	remaining: 450ms
841:	learn: 0.0001059	total: 2.38s	remaining: 447ms
842:	learn: 0.0001058	total: 2.39s	remaining: 444ms
843:	learn: 0.0001056	total: 2.39s	remaining: 442ms
844:	learn: 0.0001055	total: 2.39s	remaining: 439ms
845:	learn: 0.0001054	total: 2.39s	remaining: 436ms
846:	learn: 0.0001053	total: 2.4s	remaining: 433ms
847:	learn: 0.0001052	total: 2.4s	remaining: 430ms
848:	learn: 0.0001051	total: 2.4s	remaining: 427ms
849:	learn: 0.0001049	total: 2.4s	remaining: 424ms
850:	learn: 0.0001048	total: 2.41s	remaining: 422ms
851:	learn: 0.0001046	total: 2.41s	remaining: 419ms
852:	learn: 0.0001045	total: 2.41s	remaining: 416ms
853:	learn: 0.0001044	total: 2.42s	remaining: 413ms
854:	learn: 0.0001042	total: 2.42s	remaining: 410ms
855:	learn: 0.0001041	total: 2.42s	remaining: 407ms
856:	learn: 0.00

## Валидация

In [53]:
validation = pd.read_csv('./1/dataset_protocols_ABC.csv')

In [54]:
validation

Unnamed: 0          src_ip  sport           dst_ip  dport  proto  \
0              0   55.120.147.65  63868    170.14.68.136    443      6   
1              1    66.116.25.18  57492    218.70.73.126    443      6   
2              2  91.253.185.139  39921   243.67.106.209    443      6   
3              3  87.188.167.158  42404    27.179.73.232    443      6   
4              4    97.46.98.210  41070  215.102.164.108    443      6   
...          ...             ...    ...              ...    ...    ...   
2282        2282  172.17.240.131  40716   130.87.143.208  36508      6   
2283        2283  131.48.141.198  33524    170.14.68.136    443      6   
2284        2284  241.200.198.21  55966    170.14.68.136    443      6   
2285        2285  172.17.240.131  43136   130.87.143.208  36508      6   
2286        2286     75.9.212.91  58778    22.59.196.106    443      6   

      payload_bytes_0  payload_bytes_1  payload_bytes_2  \
0                 NaN              NaN              NaN   
1                 NaN              NaN              NaN   
2                 NaN              NaN              NaN   
3                 NaN              NaN              NaN   
4                 NaN              NaN              NaN   
...               ...              ...              ...   
2282              NaN              NaN              NaN   
2283              NaN              NaN              NaN   
2284              NaN              NaN              NaN   
2285              NaN              NaN              NaN   
2286              NaN              NaN              NaN   

                                        payload_bytes_3  ... pkt_len_3  \
0     0b9ed3fd285abf43cb4cc5b182f7587909e3b5deefba50...  ...       217   
1     1603010200010001fc0303375c0927553f6be46997f7cd...  ...       537   
2     1603010200010001fc0303d1f8735a38973f25581bfe7a...  ...       549   
3     bb444ff210cdd68116abefc327fe77b31284fa79bb6f41...  ...      1260   
4     1603010200010001fc03030741b218922521135adebb42...  ...       549   
...                                                 ...  ...       ...   
2282  a0bd01dcf423af9a3cb25e7b4e96f2a65f05d619188cbc...  ...      1005   
2283  d6c754ad279c46985a54d5d05014a5374ee063a6d9ac1e...  ...      1260   
2284  c036ea815dea6a2a778efc5aa4539b129cd8d9aab613c1...  ...      1260   
2285  433b9310b56956389520c165181cca11d32cd0acf0fbc6...  ...       856   
2286  1603010200010001fc0303ce6a5515d670dbca230500f3...  ...       549   

     pkt_len_4 pkt_len_5 pkt_len_6 pkt_len_7 pkt_len_8 pkt_len_9 pkt_len_10  \
0          137        32       409       201      1260      1260       1260   
1         1221        20        20        84      1420      1420       1045   
2           32      1380      1380      1278        32        32         32   
3          588       201       892       556       812       556       1260   
4           32       188        32        83        32      1255         32   
...        ...       ...       ...       ...       ...       ...        ...   
2282        32       358        32       146       674        32         32   
2283      1260       484      1260       426        32       201         32   
2284       680       121      1260      1260      1260      1260       1260   
2285        32       332        32       130       158       496         32   
2286      1430      1430       253        32        32        32        125   

     pkt_len_11  pkt_len_12  
0          1260        1260  
1           291         291  
2           112         335  
3           632          32  
4           204          63  
...         ...         ...  
2282        665         674  
2283       1260        1260  
2284       1260        1260  
2285         32          32  
2286         32         237  

[2287 rows x 45 columns]

In [55]:
validation = validation.drop(columns=[
    'payload_bytes_0', 
    'payload_bytes_1', 
    'payload_bytes_2', 
    'proto', 
    'Unnamed: 0', 
    'sport', 
    'dport', 
    'payload_bytes_4', 
    'payload_bytes_5', 
    'payload_bytes_6', 
    'payload_bytes_7', 
    'payload_bytes_8', 
    'payload_bytes_9', 
    'payload_bytes_10', 
    'payload_bytes_11', 
    'payload_bytes_12',
    'pkt_len_1',
    'pkt_len_2',
    'pkt_len_3',
    'pkt_len_4',
    'pkt_len_5',
    'pkt_len_6',
    'pkt_len_7',
    'pkt_len_8',
    'pkt_len_9',
    'pkt_len_10',
    'pkt_len_11',
    'pkt_len_12',
    'direction_0',
    'direction_1',
    'direction_2',
    'direction_4',
    'direction_7',
    'src_ip'
            ]
        )

In [56]:
validation['payload_bytes_3'] = validation['payload_bytes_3'].str.slice(0, 4)
validation['payload_bytes_3'] = validation['payload_bytes_3'].map(lambda x: 1 if x in ['1603', '4544', '1403', 'd500'] else 0)
validation['dst_ip'] = validation['dst_ip'].map(lambda x: 1 if x == '130.87.143.208' else 0)

In [57]:
model = GradientBoostingClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(validation)

In [58]:
validation['protocol'] = y_pred

In [59]:
answer = validation['protocol']

In [60]:
for i in range(len(answer)):
    if answer[i] == 0:
        answer[i] = 'A'
    elif answer[i] == 1:
        answer[i] = 'B'
    else:
        answer[i] = 'C'

C:\Users\emil_\AppData\Local\Temp\ipykernel_13996\3995619036.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  answer[i] = 'B'


In [61]:
#answer.name = None

In [62]:
answer

0       B
1       A
2       A
3       B
4       A
       ..
2282    C
2283    B
2284    B
2285    C
2286    A
Name: protocol, Length: 2287, dtype: object

In [63]:
answer.to_csv('answer.csv', header=False)

In [64]:
answer.value_counts()

A    1006
C    1002
B     279
Name: protocol, dtype: int64